abstract class SocialRegisterStates {}
class InitialRegisterState extends SocialRegisterStates{}
class changeRegisterState extends SocialRegisterStates{}
class RegisterSucessState extends SocialRegisterStates{}
class RegisterErrorState extends SocialRegisterStates{}
class RegisterLoadingState extends SocialRegisterStates{}
class CreateUserLoadingState extends SocialRegisterStates{}
class CreateUserSucessState extends SocialRegisterStates{}
class CreateUserErrorState extends SocialRegisterStates{}